
ATTACK_ORDER_COUNT = 5
ATTACK_TARGET_AMNT_COEF = 1.1
ATTACK_PLANET_GEVEAWAY_COEF = 0.7
ATTACK_REASONABILITY_NUM_SHIPS_INC = 50.0
ATTACK_REASONABILITY_DEFENCE_COEF_POWER = 1.0
ATTACK_REASONABILITY_DEFENCE_COEF_IF_MINE_POWER = 1.0
ATTACK_GROWTH_RATE_POWER = 1.0
ATTACK_NUM_SHIPS_POWER = 1.0

EVAL_ORDER_DISTANCE_POWER = 3.0

DEFEND_TARGET_AMNT_COEF = 1.1
DEFEND_PLANET_GEVEAWAY_COEF = 0.8

