ATTACK_ORDER_COUNT = 7
DEFEND_PLANET_GEVEAWAY_COEF = 0.8
ATTACK_REASONABILITY_DEFENCE_COEF_IF_MINE_POWER = 1.4
ATTACK_GROWTH_RATE_POWER = 1.1
EVAL_ORDER_DISTANCE_POWER = 0.6
ATTACK_PLANET_GEVEAWAY_COEF = 0.8
DEFEND_TARGET_AMNT_COEF = 1.4
ATTACK_REASONABILITY_DEFENCE_COEF_POWER = 1.4
ATTACK_NUM_SHIPS_POWER = 0.4
ATTACK_REASONABILITY_NUM_SHIPS_INC = 30
ATTACK_TARGET_AMNT_COEF = 1

